# NumPy Exercises 2

#### Write a NumPy program to create an element-wise comparison (equal, equal within a tolerance) of two given arrays.


In [1]:
import numpy as np
x = np.array([72, 79, 85, 90, 150, -135, 120, -10, 60, 100])
y = np.array([72, 79, 85, 90, 150, -135, 120, -10, 60, 100.000001])
print("Original numbers:")
print(x)
print(y)
print("Comparison - equal:")
print(np.equal(x, y))
print("Comparison - equal within a tolerance:")
print(np.allclose(x, y))

Original numbers:
[  72   79   85   90  150 -135  120  -10   60  100]
[  72.         79.         85.         90.        150.       -135.
  120.        -10.         60.        100.000001]
Comparison - equal:
[ True  True  True  True  True  True  True  True  True False]
Comparison - equal within a tolerance:
True


#### Write a NumPy program to create an array with the values 1, 7, 13, 105 and determine the size of the memory occupied by the array.

In [2]:
import numpy as np
X = np.array([1, 7, 13, 105])
print("Original array:")
print(X)
print("Size of the memory occupied by the said array:")
print("%d bytes" % (X.size * X.itemsize))

Original array:
[  1   7  13 105]
Size of the memory occupied by the said array:
32 bytes


#### Write a NumPy program to create an array of 10 zeros, 10 ones, 10 fives.

In [3]:
import numpy as np
array=np.zeros(10)
print("An array of 10 zeros:")
print(array)
array=np.ones(10)
print("An array of 10 ones:")
print(array)
array=np.ones(10)*5
print("An array of 10 fives:")
print(array)

An array of 10 zeros:
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
An array of 10 ones:
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
An array of 10 fives:
[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


#### Write a NumPy program to create an array of the integers from 30 to 70

In [4]:
import numpy as np
array=np.arange(30,71)
print("Array of the integers from 30 to70")
print(array)

Array of the integers from 30 to70
[30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53
 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70]


#### Write a NumPy program to create an array of all the even integers from 30 to 70.

In [5]:
import numpy as np
array=np.arange(30,71,2)
print("Array of all the even integers from 30 to 70")
print(array) 

Array of all the even integers from 30 to 70
[30 32 34 36 38 40 42 44 46 48 50 52 54 56 58 60 62 64 66 68 70]


#### Write a NumPy program to create a 3x3 identity matrix.

In [6]:
import numpy as np
array_2D=np.identity(3)
print('3x3 matrix:')
print(array_2D)

3x3 matrix:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### Write a NumPy program to generate a random number between 0 and 1.

In [7]:
import numpy as np
rand_num = np.random.normal(0,1,1)
print("Random number between 0 and 1:")
print(rand_num)

Random number between 0 and 1:
[-0.32643297]


#### Write a NumPy program to generate an array of 15 random numbers from a standard normal distribution.

In [8]:
import numpy as np
rand_num = np.random.normal(0,1,15)
print("15 random numbers from a standard normal distribution:")
print(rand_num)

15 random numbers from a standard normal distribution:
[ 1.88101594  1.59367245 -0.48239492  0.80497216  0.87944985 -1.32470461
  1.0806704   1.30769777 -1.99618655  0.34797255  1.53438554 -1.42011791
  0.18957976  1.09361701 -1.81832492]


#### Write a NumPy program to create a vector with values ​​ranging from 15 to 55 and print all values ​​except the first and last.

In [9]:
import numpy as np
v = np.arange(15,55)
print("Original vector:")
print(v)
print("All values except the first and last of the said vector:")
print(v[1:-1])

Original vector:
[15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38
 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54]
All values except the first and last of the said vector:
[16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39
 40 41 42 43 44 45 46 47 48 49 50 51 52 53]


#### Write a NumPy program to create a 3X4 array using and iterate over it.

In [10]:
import numpy as np
a = np.arange(10,22).reshape((3, 4))
print("Original array:")
print(a)
print("Each element of the array is:")
for x in np.nditer(a):
  print(x,end=" ")

Original array:
[[10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]]
Each element of the array is:
10 11 12 13 14 15 16 17 18 19 20 21 

In [11]:
#### Write a NumPy program to create a vector of length 10 with values ​​evenly distributed between 5 and 50.

In [12]:
import numpy as np
v = np.linspace(10, 49, 5)
print("Length 10 with values evenly distributed between 5 and 50:")
print(v)

Length 10 with values evenly distributed between 5 and 50:
[10.   19.75 29.5  39.25 49.  ]
